<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Slider routes...
Route::resource('slider', 'SliderController');
// Menu routes...
Route::resource('menu', 'MenuController');
// MenuLink routes...
Route::resource('menu-link', 'MenuLinkController');
// PageCategory routes...
Route::resource('page-category', 'PageCategoryController');
// Page routes...
Route::resource('page', 'PageController');
// ContentCategory routes...
Route::resource('content-category', 'ContentCategoryController');
// Content routes...
Route::resource('content', 'ContentController');
// ArticleCategory routes...
Route::resource('article-category', 'ArticleCategoryController');
// Article routes...
Route::resource('article', 'ArticleController');
// ArticleView routes...
Route::resource('article-view', 'ArticleViewController');
// Faq routes...
Route::resource('faq', 'FaqController');
// Quote routes...
Route::resource('quote', 'QuoteController');
// Testimonial routes...
Route::resource('testimonial', 'TestimonialController');
// ImportantPerson routes...
Route::resource('important-person', 'ImportantPersonController');