<?php

use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
*/
// User routes...
Route::apiResource('user', 'Api\UserController');
// UserPersonalInfo routes...
Route::apiResource('user-personal-info', 'Api\UserPersonalInfoController');
// UserResidentialInfo routes...
Route::apiResource('user-residential-info', 'Api\UserResidentialInfoController');
// UserEducationalInfo routes...
Route::apiResource('user-educational-info', 'Api\UserEducationalInfoController');
// UserWorkInfo routes...
Route::apiResource('user-work-info', 'Api\UserWorkInfoController');
// SocialSite routes...
Route::apiResource('social-site', 'Api\SocialSiteController');
// UserSocialAccount routes...
Route::apiResource('user-social-account', 'Api\UserSocialAccountController');
// UserSkill routes...
Route::apiResource('user-skill', 'Api\UserSkillController');
// UserLanguage routes...
Route::apiResource('user-language', 'Api\UserLanguageController');
// UserInterest routes...
Route::apiResource('user-interest', 'Api\UserInterestController');
// Module routes...
Route::apiResource('module', 'Api\ModuleController');
// Role routes...
Route::apiResource('role', 'Api\RoleController');
// Permission routes...
Route::apiResource('permission', 'Api\PermissionController');
