<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/


// User routes...
Route::resource('user', 'UserController');
// UserPersonalInfo routes...
Route::resource('user-personal-info', 'UserPersonalInfoController');
// UserResidentialInfo routes...
Route::resource('user-residential-info', 'UserResidentialInfoController');
// UserEducationalInfo routes...
Route::resource('user-educational-info', 'UserEducationalInfoController');
// UserWorkInfo routes...
Route::resource('user-work-info', 'UserWorkInfoController');
// SocialSite routes...
Route::resource('social-site', 'SocialSiteController');
// UserSocialAccount routes...
Route::resource('user-social-account', 'UserSocialAccountController');
// UserContent routes...
Route::resource('user-content', 'UserContentController');
// UserLanguage routes...
Route::resource('user-language', 'UserLanguageController');
// UserInterest routes...
Route::resource('user-interest', 'UserInterestController');
// User profile routes
Route::prefix('profile')->name('profile-')->group(function () {
    // UserAccountInfo routes...
    Route::resource('account-info', 'Profile\AccountInfoController');
    // UserPersonalInfo routes...
    Route::resource('personal-info', 'Profile\PersonalInfoController')->only(['index', 'update']);
    // UserResidentialInfo routes...
    Route::resource('residential-info', 'Profile\ResidentialInfoController')->only(['index', 'update']);
    // UserEducationalInfo routes...
    Route::resource('educational-info', 'Profile\EducationalInfoController');
    // UserWorkInfo routes...
    Route::resource('work-info', 'Profile\WorkInfoController');
    // UserSocialAccount routes...
    Route::resource('social-account', 'Profile\SocialAccountController');
    // UserContent routes...
    Route::resource('content', 'Profile\ContentController');
    // UserLanguage routes...
    Route::resource('language', 'Profile\LanguageController');
    // UserInterest routes...
    Route::resource('interest', 'Profile\InterestController');
    // ChangePassword routes...
    Route::resource('password-change', 'Profile\PasswordChangeController');
});
// Module routes...
Route::resource('module', 'ModuleController');
// Role routes...
Route::resource('role', 'RoleController');
// Permission routes...
Route::resource('permission', 'PermissionController');
// Dashboard routes...
Route::resource('dashboard', 'DashboardController');
